import type { PageMeta, PageModule, PageRoute, Surface } from '../types/page';

export interface ProductPageOverride {
  title?: string;
  navLabel?: string;
  description?: string;
  surface?: Surface;
  navCategory?: string;
  navOrder?: number;
  hideFromNav?: boolean;
  path?: string;
}

export const PRIMARY_NAV_ORDER = [
  'dashboard',
  'markets',
  'trade',
  'derivatives',
  'signals',
  'predictions',
  'portfolio',
  'backtests',
  'research',
  'alerts',
  'account',
] as const;

export const PRIMARY_NAV_LABELS: Record<string, string> = {
  dashboard: 'Dashboard',
  markets: 'Markets',
  trade: 'Trade',
  derivatives: 'Derivatives',
  signals: 'Signals',
  predictions: 'AI',
  portfolio: 'Portfolio',
  backtests: 'Backtests',
  research: 'Research',
  alerts: 'Alerts',
  account: 'Account',
};

export const SYSTEM_NAV_ORDER = [
  'overview',
  'control-center',
  'ingestors',
  'trainer',
  'orchestrator',
  'risk-controllers',
  'traders',
  'execution',
  'exchanges',
  'config',
  'logs',
  'audit-ledger',
  'scripts',
  'build-validation',
  'coverage',
  'migrations',
  'users',
  'ai-tools',
  'readiness',
  'reports',
  'quarantine',
  'evidence',
  'executive-summary',
  'build-code-review',
] as const;

export const SYSTEM_NAV_LABELS: Record<string, string> = {
  overview: 'Overview',
  'control-center': 'Ops Center',
  ingestors: 'Ingestors',
  trainer: 'Trainer',
  orchestrator: 'Orchestrator',
  'risk-controllers': 'Risk Controllers',
  traders: 'Traders',
  execution: 'Execution',
  exchanges: 'Exchanges',
  config: 'Config',
  logs: 'Logs',
  'audit-ledger': 'Audit Ledger',
  scripts: 'Scripts',
  'build-validation': 'Build Validation',
  coverage: 'Coverage',
  migrations: 'Migrations',
  users: 'Users',
  'ai-tools': 'AI Tools',
  readiness: 'Readiness',
  reports: 'Reports',
  quarantine: 'Position Quarantine',
  evidence: 'Evidence',
  'executive-summary': 'Executive Summary',
  'build-code-review': 'Build / Code Review',
};

export const PAGE_OVERRIDES: Record<string, ProductPageOverride> = {
  'mission-control': {
    title: 'Dashboard',
    navLabel: 'Dashboard',
    description: 'Trader home for market state, active signals, portfolio risk, and readiness.',
    surface: 'app',
    navCategory: 'dashboard',
    navOrder: 10,
    path: '/dashboard',
  },
  markets: {
    title: 'Markets',
    navLabel: 'Markets',
    description: 'AI-powered market screener with derivatives, funding, liquidation, signal, and data coverage columns.',
    surface: 'public',
    navCategory: 'markets',
    navOrder: 10,
    path: '/markets',
  },
  symbols: {
    title: 'Symbols',
    navLabel: 'Symbols',
    description: 'Symbol universe, favorites, exchange availability, and tradability coverage.',
    surface: 'app',
    navCategory: 'markets',
    navOrder: 20,
    hideFromNav: true,
    path: '/markets/symbols',
  },
  market: {
    title: 'Market Detail',
    navLabel: 'Market Detail',
    description: 'Symbol detail with chart, derivatives, signals, predictions, order flow, and source coverage.',
    surface: 'public',
    navCategory: 'markets',
    navOrder: 30,
    path: '/market/:symbol?',
  },
  trader: {
    title: 'Trade',
    navLabel: 'Trade',
    description: 'Modular live trading terminal with chart, book, tape, order ticket, positions, executions, and risk pre-check.',
    surface: 'app',
    navCategory: 'trade',
    navOrder: 10,
    path: '/trade',
  },
  'paper-trading': {
    title: 'Live Trading',
    navLabel: 'Live Trading',
    description: 'Execution account reporting and fill-gate evidence inside the trading workflow.',
    surface: 'app',
    navCategory: 'trade',
    navOrder: 20,
    hideFromNav: true,
    path: '/trade/paper',
  },
  'liquidation-bridge': {
    title: 'Derivatives',
    navLabel: 'Derivatives',
    description: 'Liquidations, funding, OI, long/short, basis, and exchange comparison coverage.',
    surface: 'app',
    navCategory: 'derivatives',
    navOrder: 10,
    path: '/derivatives',
  },
  signals: {
    title: 'Signals',
    navLabel: 'Signals',
    description: 'Evidence-first active, pending, expired, rejected, and executed signal stream.',
    surface: 'app',
    navCategory: 'signals',
    navOrder: 10,
    path: '/signals',
  },
  // trainer-prediction-monitor stays on admin surface at its registered path
  // The 'ai-predictions' page is now a dedicated app-surface page at /ai-predictions
  'trainer-prediction-monitor': {
    title: 'Trainer Prediction Monitor',
    navLabel: 'Trainer Monitor',
    description: 'Evidence packets, liveness confidence, prediction matrix, and realized-vs-predicted.',
    surface: 'admin',
    navCategory: 'trainer',
    navOrder: 30,
    path: '/admin/trainer-prediction-monitor',
  },
  'ai-brain': {
    title: 'Model State',
    navLabel: 'Model State',
    description: 'Model state, feature drivers, uncertainty, and latest generated decisions.',
    surface: 'system',
    navCategory: 'predictions',
    navOrder: 20,
    hideFromNav: true,
    path: '/admin/model-state',
  },
  positions: {
    title: 'Portfolio',
    navLabel: 'Portfolio',
    description: 'Positions, balances, exposure, PnL, liquidation risk, and user-facing risk state.',
    surface: 'app',
    navCategory: 'portfolio',
    navOrder: 10,
    path: '/portfolio',
  },
  executions: {
    title: 'Executions',
    navLabel: 'Executions',
    description: 'Orders, fills, rejected orders, slippage, fees, venue response status, and strategy context.',
    surface: 'app',
    navCategory: 'portfolio',
    navOrder: 20,
    path: '/portfolio/executions',
  },
  history: {
    title: 'History',
    navLabel: 'History',
    description: 'Account, trade, signal, and portfolio history with symbol, strategy, exchange, and mode filters.',
    surface: 'app',
    navCategory: 'portfolio',
    navOrder: 30,
    path: '/portfolio/history',
  },
  'strategy-backtesting': {
    title: 'Backtests',
    navLabel: 'Backtests',
    description: 'Strategy replay, equity curve, drawdown, expectancy, and trade-by-trade evidence.',
    surface: 'app',
    navCategory: 'backtests',
    navOrder: 10,
    path: '/backtests',
  },
  replay: {
    title: 'Replay',
    navLabel: 'Replay',
    description: 'Trader-facing signal and strategy replay for review.',
    surface: 'app',
    navCategory: 'backtests',
    navOrder: 20,
    hideFromNav: true,
    path: '/replay',
  },
  'market-intelligence': {
    title: 'Research',
    navLabel: 'Research',
    description: 'Market intelligence, alt-data coverage, technical context, and source freshness.',
    surface: 'app',
    navCategory: 'research',
    navOrder: 10,
    path: '/research',
  },
  'technical-analysis': {
    title: 'Technical Analysis',
    navLabel: 'Technical Analysis',
    description: 'Chart overlays, indicators, support/resistance, trend regime, and volatility context.',
    surface: 'app',
    navCategory: 'research',
    navOrder: 20,
    hideFromNav: true,
    path: '/research/technical-analysis',
  },
  alerts: {
    title: 'Alerts',
    navLabel: 'Alerts',
    description: 'Price, OI, liquidation, funding, signal, risk, and system alert coverage.',
    surface: 'app',
    navCategory: 'alerts',
    navOrder: 10,
    path: '/alerts',
  },
  'account-settings': {
    title: 'Account Settings',
    navLabel: 'Account',
    description: 'Profile, linked exchange accounts, watchlist, and password management for the signed-in trader.',
    surface: 'app',
    navCategory: 'account',
    navOrder: 10,
    path: '/account-settings',
  },

  'system-health': {
    title: 'System Overview',
    navLabel: 'Overview',
    surface: 'system',
    navCategory: 'overview',
    navOrder: 10,
    path: '/admin/system',
  },
  'admin-war-room': {
    title: 'Ops Center',
    navLabel: 'Ops Center',
    surface: 'system',
    navCategory: 'control-center',
    navOrder: 10,
    path: '/admin',
  },
  'monitor-center': {
    title: 'Monitor Center',
    navLabel: 'Monitor Center',
    surface: 'admin',
    navCategory: 'observability',
    navOrder: 20,
    path: '/admin/monitor-center',
  },
  ingestors: {
    title: 'Ingestors',
    navLabel: 'Ingestors',
    surface: 'system',
    navCategory: 'ingestors',
    navOrder: 10,
    path: '/admin/ingestors',
  },
  'trainer-admin': {
    title: 'Trainer',
    navLabel: 'Trainer',
    surface: 'system',
    navCategory: 'trainer',
    navOrder: 10,
    path: '/admin/trainer',
  },
  'orchestrator-admin': {
    title: 'Orchestrator',
    navLabel: 'Orchestrator',
    surface: 'system',
    navCategory: 'orchestrator',
    navOrder: 10,
    path: '/admin/orchestrator',
  },
  'risk-control': {
    title: 'Risk Controllers',
    navLabel: 'Risk Controllers',
    surface: 'admin',
    navCategory: 'risk-controllers',
    navOrder: 10,
    path: '/admin/risk',
  },
  'strategy-admin': {
    title: 'Traders',
    navLabel: 'Traders',
    surface: 'admin',
    navCategory: 'traders',
    navOrder: 10,
    path: '/admin/traders',
  },
  'execution-admin': {
    title: 'Execution Control',
    navLabel: 'Execution',
    surface: 'admin',
    navCategory: 'execution',
    navOrder: 10,
    path: '/admin/execution',
  },
  'exchange-manager': {
    title: 'Exchanges',
    navLabel: 'Exchanges',
    surface: 'admin',
    navCategory: 'exchanges',
    navOrder: 10,
    path: '/admin/exchanges',
  },
  'config-admin': {
    title: 'Config',
    navLabel: 'Config',
    surface: 'admin',
    navCategory: 'config',
    navOrder: 10,
    path: '/admin/config',
  },
  'logs-errors': {
    title: 'Logs',
    navLabel: 'Logs',
    surface: 'system',
    navCategory: 'logs',
    navOrder: 10,
    path: '/admin/logs',
  },
  'audit-ledger': {
    title: 'Audit Ledger',
    navLabel: 'Audit Ledger',
    surface: 'system',
    navCategory: 'audit-ledger',
    navOrder: 10,
    path: '/admin/audit',
  },
  'script-registry': {
    title: 'Scripts',
    navLabel: 'Scripts',
    surface: 'system',
    navCategory: 'scripts',
    navOrder: 10,
    path: '/admin/scripts',
  },
  'build-validation-status': {
    title: 'Build Validation',
    navLabel: 'Build Validation',
    surface: 'system',
    navCategory: 'build-validation',
    navOrder: 10,
    path: '/admin/build-validation',
  },
  'coverage-system-atlas': {
    title: 'Coverage',
    navLabel: 'Coverage',
    surface: 'system',
    navCategory: 'coverage',
    navOrder: 10,
    path: '/admin/coverage',
  },
  'permanent-migration': {
    title: 'Migrations',
    navLabel: 'Migrations',
    surface: 'system',
    navCategory: 'migrations',
    navOrder: 10,
    path: '/admin/migrations',
  },
  'user-status': {
    title: 'Simple Status',
    navLabel: 'Simple Status',
    surface: 'public',
    navCategory: 'status',
    hideFromNav: true,
    navOrder: 10,
    path: '/status-simple',
  },
  'claude-admin-ai': {
    title: 'AI Tools',
    navLabel: 'AI Tools',
    surface: 'system',
    navCategory: 'ai-tools',
    navOrder: 10,
    path: '/admin/ai-tools',
  },
  'live-readiness': {
    title: 'Readiness',
    navLabel: 'Readiness',
    surface: 'admin',
    navCategory: 'readiness',
    navOrder: 10,
    path: '/admin/readiness',
  },
  'mobile-iphone-readiness': {
    title: 'Mobile Readiness',
    navLabel: 'Mobile',
    surface: 'system',
    navCategory: 'readiness',
    navOrder: 20,
    path: '/admin/readiness/mobile',
  },
  'report-center': {
    title: 'Reports',
    navLabel: 'Reports',
    surface: 'system',
    navCategory: 'reports',
    navOrder: 10,
    path: '/admin/reports',
  },
  'external-manual-position-quarantine': {
    title: 'Position Quarantine',
    navLabel: 'Quarantine',
    surface: 'admin',
    navCategory: 'quarantine',
    navOrder: 10,
    path: '/admin/external-manual-position-quarantine',
  },
  'operator-proof-dashboard': {
    title: 'Evidence',
    navLabel: 'Evidence',
    surface: 'admin',
    navCategory: 'evidence',
    navOrder: 10,
    path: '/admin/evidence',
  },
  'executive-status': {
    title: 'Executive Summary',
    navLabel: 'Executive Summary',
    surface: 'system',
    navCategory: 'executive-summary',
    navOrder: 10,
    path: '/system/executive-summary',
  },
  'codex-review-center': {
    title: 'Build / Code Review',
    navLabel: 'Build / Code Review',
    surface: 'system',
    navCategory: 'build-code-review',
    navOrder: 10,
    path: '/system/build-code-review',
  },
};

export const MERGED_LEGACY_PATHS: Record<string, string> = {
  '/system': '/admin/system',
  '/mission-control': '/dashboard',
  '/admin/mission-control': '/dashboard',
  '/operator-proof': '/admin/evidence',
  '/admin/war-room': '/admin',
  '/admin/permanent-migration': '/admin/migrations',
  '/admin/coverage-system-atlas': '/admin/coverage',
  '/admin/script-registry': '/admin/scripts',
  '/admin/trainer-prediction-monitor': '/ai-predictions',
  '/ai-predictions/model-state': '/ai-predictions',
  '/admin/symbols': '/markets',
  '/markets/symbols': '/markets',
  '/admin/market-intelligence': '/research',
  '/admin/ai-brain': '/admin/model-state',
  '/admin/signals': '/signals',
  '/admin/executions': '/portfolio/executions',
  '/admin/positions': '/portfolio',
  '/admin/risk-control': '/admin/risk',
  '/admin/exchange-manager': '/admin/exchanges',
  '/admin/config-admin': '/admin/config',
  '/admin/strategy-admin': '/admin/traders',
  '/system/strategy-controls': '/admin/traders',
  '/system/ingestors': '/admin/ingestors',
  '/admin/technical-analysis': '/research',
  '/research/technical-analysis': '/research',
  '/admin/liquidation-bridge': '/derivatives',
  '/admin/strategy-backtesting': '/backtests',
  '/admin/logs-errors': '/admin/logs',
  '/admin/trainer-admin': '/admin/trainer',
  '/admin/orchestrator-admin': '/admin/orchestrator',
  '/admin/execution-admin': '/admin/execution',
  '/admin/paper-trading': '/trade',
  '/trade/paper': '/trade',
  '/admin/replay': '/backtests',
  // NOTE: '/backtests/replay' is now a real app page — do NOT add a redirect here
  '/admin/audit-ledger': '/admin/audit',
  '/admin/live-readiness': '/admin/readiness',
  '/admin/claude-admin-ai': '/admin/ai-tools',
  '/admin/ollama-local-assistant': '/admin/ai-tools',
  '/admin/codex-review-center': '/system/build-code-review',
  '/admin/report-center': '/admin/reports',
  '/admin/executive-status': '/system/executive-summary',
  '/admin/build-validation-status': '/admin/build-validation',
  '/admin/operator-proof-dashboard': '/admin/evidence',
  '/admin/mobile-iphone-readiness': '/admin/readiness/mobile',
  '/system/control-center': '/admin',
  '/system/health': '/admin/system',
  '/system/risk-controllers': '/admin/risk',
  '/system/exchanges': '/admin/exchanges',
  '/system/position-quarantine': '/admin/traders',
  '/system/config': '/admin/config',
  '/system/logs': '/admin/logs',
  '/system/trainer': '/admin/trainer',
  '/system/orchestrator': '/admin/orchestrator',
  '/system/execution': '/admin/execution',
  '/system/audit-ledger': '/admin/audit',
  '/system/readiness': '/admin/readiness',
  '/system/ai-tools': '/admin/ai-tools',
  '/system/reports': '/admin/reports',
  '/system/build-validation': '/admin/build-validation',
  '/system/evidence': '/admin/evidence',
  '/system/readiness/mobile': '/admin/readiness/mobile',
  '/trader': '/trade',
  '/history': '/portfolio/history',
  '/landing-legacy': '/landing',
};

export function resolvePageModule(page: PageModule): PageModule {
  const override = PAGE_OVERRIDES[page.meta.id];
  if (!override) return page;
  const meta: PageMeta = {
    ...page.meta,
    title: override.title ?? page.meta.title,
    navLabel: override.navLabel ?? page.meta.navLabel,
    description: override.description ?? page.meta.description,
    surface: override.surface ?? page.meta.surface,
    navCategory: override.navCategory ?? page.meta.navCategory,
    navOrder: override.navOrder ?? page.meta.navOrder,
    hideFromNav: override.hideFromNav ?? page.meta.hideFromNav,
  };
  const route: PageRoute = { path: override.path ?? page.route.path };
  return { ...page, meta, route };
}
