from __future__ import annotations


DEGRADED_SOURCE_OK = "DEGRADED_SOURCE_OK"
DEGRADED_SOURCE_STALE = "DEGRADED_SOURCE_STALE"
DEGRADED_SOURCE_MISSING = "DEGRADED_SOURCE_MISSING"
DEGRADED_SOURCE_UNUSED = "DEGRADED_SOURCE_UNUSED"


_ALLOWED_DEGRADED_SOURCE_STATES = frozenset(
    {
        DEGRADED_SOURCE_OK,
        DEGRADED_SOURCE_STALE,
        DEGRADED_SOURCE_MISSING,
        DEGRADED_SOURCE_UNUSED,
    }
)


_FAIL_CLOSED_TRIGGER_STATES = frozenset(
    {
        DEGRADED_SOURCE_STALE,
        DEGRADED_SOURCE_MISSING,
    }
)
