/home/wali/Desktop/AI BOT/logs/hybrid_trainer.log {
    daily
    rotate 1
    maxage 1
    missingok
    notifempty
    copytruncate
    compress
    delaycompress
    dateext
    dateformat -%Y%m%d
}

