HEALTH_STATUS_HEALTHY = "HEALTHY"
HEALTH_STATUS_DEGRADED = "DEGRADED"
HEALTH_STATUS_CRITICAL = "CRITICAL"
HEALTH_STATUS_UNKNOWN = "UNKNOWN"

HEALTH_REASON_PREDICTION_AGE_DEGRADED = "prediction_age_degraded"
HEALTH_REASON_GPU_BATCH_AGE_DEGRADED = "gpu_batch_age_degraded"
HEALTH_REASON_PROPOSAL_AGE_DEGRADED = "proposal_age_degraded"
HEALTH_REASON_PREDICTION_AGE_CRITICAL = "prediction_age_critical"
HEALTH_REASON_GPU_BATCH_AGE_CRITICAL = "gpu_batch_age_critical"
HEALTH_REASON_PROPOSAL_AGE_CRITICAL = "proposal_age_critical"
HEALTH_REASON_PREDICTION_STREAM_ZERO_GROWTH = "prediction_stream_zero_growth"
HEALTH_REASON_PREDICTION_WORKER_DEAD = "prediction_worker_dead"
HEALTH_REASON_FATAL_LOG_SIGNATURE_OBSERVED = "fatal_log_signature_observed"
HEALTH_REASON_NO_SIGNALS_OBSERVED = "no_signals_observed"

_ALLOWED_HEALTH_STATUSES = frozenset(
    {
        HEALTH_STATUS_HEALTHY,
        HEALTH_STATUS_DEGRADED,
        HEALTH_STATUS_CRITICAL,
        HEALTH_STATUS_UNKNOWN,
    }
)
_ALLOWED_HEALTH_REASONS = frozenset(
    {
        HEALTH_REASON_PREDICTION_AGE_DEGRADED,
        HEALTH_REASON_GPU_BATCH_AGE_DEGRADED,
        HEALTH_REASON_PROPOSAL_AGE_DEGRADED,
        HEALTH_REASON_PREDICTION_AGE_CRITICAL,
        HEALTH_REASON_GPU_BATCH_AGE_CRITICAL,
        HEALTH_REASON_PROPOSAL_AGE_CRITICAL,
        HEALTH_REASON_PREDICTION_STREAM_ZERO_GROWTH,
        HEALTH_REASON_PREDICTION_WORKER_DEAD,
        HEALTH_REASON_FATAL_LOG_SIGNATURE_OBSERVED,
        HEALTH_REASON_NO_SIGNALS_OBSERVED,
    }
)
