export const PUBLIC_TRADER_FORBIDDEN_TERMS = [
  'AI BOT V2',
  'Control Plane',
  'Operator',
  'War Room',
  'Mission Control',
  'Codex',
  'Claude',
  'Ollama',
  'payload',
  'raw payload',
  'proof',
  'gap matrix',
  'local role',
  'role override',
  'fake admin',
  'session role',
  'migration',
  'script',
  'build validation',
  'coverage',
  'quarantine',
  'raw audit ledger',
] as const;

export const STATUS_PAGE_FORBIDDEN_TERMS = [
  'stack trace',
  'debug json',
  'raw json',
  'worker exception',
  'api key',
  'secret',
  'private key',
  'codex',
  'migration',
  'coverage',
  'script registry',
] as const;

export const ADMIN_ALLOWED_TERMS = [
  'Admin',
  'Audit',
  'Evidence',
  'Scripts',
  'Build validation',
  'Coverage',
  'Migrations',
  'Codex',
  'AI tools',
] as const;
