export const PUBLIC_PAGE_PATHS = ['/', '/landing', '/status', '/status-simple', '/login'] as const;

export const TRADER_PAGE_PATHS = [
  '/dashboard',
  '/account-settings',
  '/markets',
  '/markets/symbols',
  '/market/BTCUSDT',
  '/chart/BTCUSDT',
  '/trade',
  '/trade/paper',
  '/derivatives',
  '/signals',
  '/ai-predictions',
  '/ai-predictions/model-state',
  '/portfolio',
  '/portfolio/executions',
  '/portfolio/history',
  '/risk',
  '/audit-ledger',
  '/live-canary',
  '/backtests',
  '/backtests/replay',
  '/research',
  '/research/technical-analysis',
  '/alerts',
] as const;

export const ADMIN_PAGE_PATHS = [
  '/admin',
  '/admin/system',
  '/admin/monitor-center',
  '/admin/ingestors',
  '/admin/trainer',
  '/admin/trainer-admin',
  '/admin/trainer-prediction-monitor',
  '/admin/signal-explainability',
  '/admin/orchestrator',
  '/admin/risk',
  '/admin/traders',
  '/admin/execution',
  '/admin/exchanges',
  '/admin/config',
  '/admin/logs',
  '/admin/audit',
  '/admin/scripts',
  '/admin/build-validation',
  '/admin/coverage',
  '/admin/migrations',
  '/admin/ai-tools',
  '/admin/readiness',
  '/admin/readiness/mobile',
  '/admin/reports',
  '/admin/external-manual-position-quarantine',
  '/admin/executive-status',
  '/admin/codex-review-center',
] as const;

export const SUPERADMIN_PAGE_PATHS = [
  '/admin/evidence',
] as const;

export const ALL_PAGE_PATHS = [
  ...PUBLIC_PAGE_PATHS,
  ...TRADER_PAGE_PATHS,
  ...ADMIN_PAGE_PATHS,
  ...SUPERADMIN_PAGE_PATHS,
] as const;

export const REVIEWER_ONLY_ADMIN_PATHS = [
  '/system/readiness',
  '/system/reports',
  '/system/audit-ledger',
  '/system/scripts',
  '/system/build-validation',
  '/system/coverage',
  '/system/migrations',
  '/system/ai-tools',
] as const;

export const VIEWER_VISIBLE_ADMIN_PATHS = [
  '/dashboard',
  '/markets',
  '/trade',
  '/signals',
  '/ai-predictions',
  '/portfolio',
  '/backtests',
  '/research',
] as const;

export const PAGES_WITH_DANGEROUS_CONTROLS = [
  {
    path: '/system/risk-controllers',
    controls: ['disable_kill_switch', 'disable_mandatory_stop', 'increase_daily_loss_limit'],
  },
  {
    path: '/system/config',
    controls: ['enable_live_trading', 'enable_adjust_leverage', 'switch_paper_to_live', 'enable_cross_margin'],
  },
  {
    path: '/system/strategy-controls',
    controls: ['enable_hedge_dca'],
  },
  {
    path: '/system/execution',
    controls: ['switch_paper_to_live', 'increase_max_position_size', 'add_live_api_keys'],
  },
  {
    path: '/system/readiness',
    controls: ['enable_live_trading', 'increase_leverage'],
  },
] as const;

export const LEGACY_REDIRECTS = {
  '/landing-legacy': '/landing',
  '/system': '/admin',
  '/mission-control': '/dashboard',
  '/admin/mission-control': '/dashboard',
  '/operator-proof': '/admin/reports',
  '/admin/war-room': '/admin',
  '/admin/permanent-migration': '/admin/tools',
  '/admin/coverage-system-atlas': '/admin/tools',
  '/admin/script-registry': '/admin/tools',
  '/ai-predictions/model-state': '/ai-predictions',
  '/markets/symbols': '/markets',
  '/admin/symbols': '/markets',
  '/admin/market-intelligence': '/research',
  '/admin/ai-brain': '/admin/model-state',
  '/admin/signals': '/signals',
  '/admin/executions': '/portfolio/executions',
  '/admin/positions': '/portfolio',
  '/admin/risk-control': '/admin/risk',
  '/admin/exchange-manager': '/admin/exchanges',
  '/admin/config-admin': '/admin/config',
  '/admin/strategy-admin': '/admin/orchestration',
  '/system/strategy-controls': '/admin/orchestration',
  '/system/ingestors': '/admin/data',
  '/admin/technical-analysis': '/research',
  '/research/technical-analysis': '/research',
  '/admin/liquidation-bridge': '/derivatives',
  '/admin/strategy-backtesting': '/backtests',
  '/admin/logs-errors': '/admin/logs',
  '/admin/orchestrator-admin': '/admin/orchestration',
  '/admin/execution-admin': '/admin/execution',
  // '/trade/paper' is a real page (paper-trading module), not a redirect —
  // a redirect entry for it would shadow the page. The legacy admin alias lands on it.
  '/admin/paper-trading': '/trade/paper',
  '/backtests/replay': '/backtests',
  '/admin/replay': '/backtests',
  '/admin/audit-ledger': '/admin/audit',
  '/ingestors': '/markets/ingestors',
  '/providers': '/markets/ingestors',
  '/admin/claude-admin-ai': '/admin/tools',
  '/admin/ollama-local-assistant': '/admin/tools',
  '/admin/report-center': '/admin/reports',
  '/admin/build-validation-status': '/admin/tools',
  '/admin/operator-proof-dashboard': '/admin/evidence',
  '/admin/mobile-iphone-readiness': '/admin/risk',
  '/system/control-center': '/admin',
  '/system/health': '/admin',
  '/system/risk-controllers': '/admin/risk',
  '/system/exchanges': '/admin/exchanges',
  '/system/position-quarantine': '/admin/risk',
  '/system/config': '/admin/config',
  '/system/logs': '/admin/logs',
  '/system/model-state': '/admin/intelligence',
  '/system/trainer': '/admin/intelligence',
  '/system/orchestrator': '/admin/orchestration',
  '/system/execution': '/admin/execution',
  '/system/audit-ledger': '/admin/audit',
  '/system/readiness': '/admin/risk',
  '/system/ai-tools': '/admin/tools',
  '/system/reports': '/admin/reports',
  '/system/build-validation': '/admin/tools',
  '/system/executive-summary': '/admin/executive-status',
  '/system/build-code-review': '/admin/codex-review-center',
  '/system/evidence': '/admin/reports',
  '/system/readiness/mobile': '/admin/risk',
  '/trader': '/trade',
  '/history': '/portfolio/history',
} as const;
