from pathlib import Path


def test_service_milestone_forbidden_tokens():
    root = Path(__file__).resolve().parents[4]
    scan_files = (
        root / "app/services/trainer_parity/__init__.py",
        root / "app/services/trainer_parity/errors.py",
        root / "app/services/trainer_parity/evaluation.py",
        root / "app/services/trainer_parity/liveness_service.py",
        root / "tests/unit/services/trainer_parity/test_public_surface.py",
        root / "tests/unit/services/trainer_parity/test_init_module_does_not_load_redis_when_imported.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_reader_without_latest_stream_id.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_reader_with_non_callable_latest_stream_id.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_base_inputs_object.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_tuple_prediction_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_tuple_proposal_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_observation_in_prediction_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_observation_in_proposal_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_growth_window_config.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_callable_clock.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_clock_returning_non_int.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_clock_returning_negative_int.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_calls_clock_exactly_once.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_str_prediction_stream_name.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_empty_prediction_stream_name.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_str_proposal_stream_name.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_empty_proposal_stream_name.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_identical_stream_names.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_non_int_max_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_zero_max_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_rejects_negative_max_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_appends_prediction_observation_to_prediction_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_caps_prediction_history_at_max.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_caps_proposal_history_at_max.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_does_not_mutate_supplied_histories.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_returns_trainer_liveness_evaluation_dataclass.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_passes_now_ms_into_compose.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_returns_snapshot_with_growth_from_history.py",
        root / "tests/unit/services/trainer_parity/test_evaluate_propagates_collector_errors.py",
        root / "tests/unit/services/trainer_parity/test_service_does_not_import_factory_or_url_env.py",
        root / "tests/unit/services/trainer_parity/test_service_milestone_forbidden_tokens.py",
    )
    tokens = (
        "import " + "redis",
        "from " + "redis",
        "redis" + "." + "asyncio",
        "redis" + "." + "Redis(",
        "redis" + "." + "Redis" + "." + "from_url(",
        "aio" + "redis",
        "hire" + "dis",
        "time" + "." + "time(",
        "time" + "." + "monotonic(",
        "time" + "." + "perf_counter(",
        "datetime" + "." + "now(",
        "datetime" + "." + "utcnow(",
        "os" + "." + "environ",
        "subprocess" + ".",
        "subprocess" + "." + "run",
        "subprocess" + "." + "Popen",
        "socket" + ".",
        "socket" + "." + "socket",
        "socket" + "." + "create_connection",
        "urllib" + "." + "request",
        "urllib" + "." + "parse",
        "requests" + ".",
        "http" + "x.",
        "aio" + "http.",
        "threading" + "." + "Thread",
        "threading" + "." + "Timer",
        "asyncio" + "." + "create_task",
        "asyncio" + "." + "run",
        "print" + "(",
        "sys" + "." + "stdout.write",
        "sys" + "." + "stderr.write",
        "logging" + "." + "getLogger",
        "logger" + ".",
        "logging" + ".",
        "FastAPI" + " startup",
        "lifespan" + " handler",
        "background" + " task",
        "x" + "add",
        "x" + "del",
        "x" + "trim",
        "xgroup" + "_",
        "xgroup" + "_create",
        "xgroup" + "_destroy",
        "xgroup" + "_setid",
        "x" + "ack",
        "x" + "claim",
        "set" + "(",
        "m" + "set",
        "set" + "nx",
        "set" + "ex",
        "p" + "set" + "ex",
        "get" + "set",
        "h" + "set",
        "hm" + "set",
        "h" + "del",
        "h" + "set" + "nx",
        "l" + "push",
        "r" + "push",
        "l" + "pop",
        "r" + "pop",
        "l" + "rem",
        "l" + "trim",
        "s" + "add",
        "s" + "rem",
        "s" + "move",
        "z" + "add",
        "z" + "rem",
        "z" + "incrby",
        "z" + "remrangebyscore",
        "z" + "remrangebyrank",
        "del" + "ete",
        "un" + "link",
        "ex" + "pire",
        "pex" + "pire",
        "per" + "sist",
        "script" + "_load",
        "eval" + "sha",
        "eval" + "(",
        "flush" + "db",
        "flush" + "all",
        "config" + "_set",
        "config" + "_get",
        "config" + "_resetstat",
        "pub" + "sub",
        "publish" + "(",
        "connection" + "_pool",
        "from v2.backend.app.adapters." + "redis_v2." + "factory",
        "from v2.backend.app.adapters." + "redis_v2." + "url_env",
        "import v2.backend.app.adapters." + "redis_v2." + "factory",
        "import v2.backend.app.adapters." + "redis_v2." + "url_env",
        "v2.backend.app.adapters." + "redis_v2." + "factory",
        "v2.backend.app.adapters." + "redis_v2." + "url_env",
    )
    for file_path in scan_files:
        content = file_path.read_text(encoding="utf-8")
        for token in tokens:
            assert content.count(token) == 0, f"{file_path}: {token}"
