from v2.backend.app.domain.paper_execution_ledger import (
    PAPER_LEDGER_REASON_MIRROR_ALLOW_PROCEED_LONG,
    PAPER_LEDGER_REASON_MIRROR_ALLOW_PROCEED_SHORT,
    PAPER_LEDGER_REASON_MIRROR_DENY_DEFAULT,
    PAPER_LEDGER_REASON_MIRROR_DENY_ORCHESTRATOR_ABSTAINED,
    PAPER_LEDGER_REASON_MIRROR_DENY_ORCHESTRATOR_HELD,
)


def test_reason_constants_carry_correct_prefix() -> None:
    assert PAPER_LEDGER_REASON_MIRROR_ALLOW_PROCEED_LONG.startswith("mirror_allow_")
    assert PAPER_LEDGER_REASON_MIRROR_ALLOW_PROCEED_SHORT.startswith("mirror_allow_")
    assert PAPER_LEDGER_REASON_MIRROR_DENY_ORCHESTRATOR_ABSTAINED.startswith("mirror_deny_")
    assert PAPER_LEDGER_REASON_MIRROR_DENY_ORCHESTRATOR_HELD.startswith("mirror_deny_")
    assert PAPER_LEDGER_REASON_MIRROR_DENY_DEFAULT.startswith("mirror_deny_")
